### ISSUE TITLE
Format must be specified

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/memgatorBulkDownload#1]
The README seems to imply that there is a "default format". When I:
`python3 download.py -l uris.txt`
...I am told, "download: error: one of the arguments -j/--json -n/--link -c/--cdxj is required". If a format parameter is required, then there is no "default". Which is it?

**Comment by N0taN3rd** [comment]
@machawk1 right you are. Looks like I should have put a **not ready for prime time** warning fixes incoming
