### ISSUE TITLE
Empty directory after running trivial example

### ISSUE THREAD

**Issue by machawk1** [N0taN3rd/memgatorBulkDownload#2]
Using f5b33767d0be76de521ca7f12dc7282bc019f4cd and Python 3.6.4. I created a \r\n delimited list of 3 URIs. I start my local MemGator 1.0-rc7 (on the default port) and ran `python3 download.py -j -l uris.txt`. A `timemaps` directory is created but no files are contained within. The aforementioned command returns very quickly with MemGator showing any sign of being interacted with when invoked via `memgator -V server`.

**Comment by N0taN3rd** [comment]
@machawk1 Looks like I should have put a **not ready for prime time** warning fixes incoming
